import Head from 'next/head'
import Main from '../../components/Main'
import Navbar from '../../components/Navbar'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>TubeTrends</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      
      <section classname="text-gray-600 body-font" className={styles.section1}>
  <div classname="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center" className={styles.lmao}>
    <div classname="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0" className={styles.section1image}>
      <Image classname="object-cover object-center rounded" alt="hero" src="/hell.jpg" width={500} height={250}/>
    </div>
    <div classname="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center" className={styles.content1}>
      <h1 classname="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Before they sold out
        <br classname="hidden lg:inline-block"/>readymade gluten
      </h1>
      <p classname="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
      <div classname="flex justify-center" >
        <button classname="inline-flex text-white bg-yellow-500 border-0 py-2 px-6 focus:outline-none hover:bg-yellow-600 rounded text-lg" className={styles.btn1}>Button</button>
        <button classname="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"className={styles.btn2}>Button</button>
      </div>
    </div>
  </div>
</section>
<section className="text-gray-600 body-font" >
  <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center" className={styles.lmao}>
    <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center"  className={styles.sect2}>
      <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Before they sold out
        <br className="hidden lg:inline-block"/>readymade gluten
      </h1>
      <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
      <div className="flex justify-center">
        <button className="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg" className={styles.btn3}>Button</button>
        <button className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"className={styles.btn4}>Button</button>
      </div>
    </div>
    <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <Image className="object-cover object-center rounded" alt="hero" src="/aha.jpg" height={250} width={500}/>
    </div>
  </div>
</section>
    </>
  )
}
